spring:
  application:
    name: usercenter
  profiles:
    active: dev
server:
  port: 12333
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lsj.usercenter.model.entity
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match:
        - '/**'
      packages-to-scan:
        - com.lsj.usercenter.controller
