spring:
  application:
    name: usercenter
  datasource:
    url: jdbc:mysql://47.109.85.240:13306/planetcode?useSSL=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hcs@2023

  data:
    redis:
      database: 0
      host: 47.109.85.240
      port: 16379
      password: Huawei@1234
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

imgtp:
  pic:
    email: 18292885932@163.com
    password: tc_mutouren